### PR TITLE
Port more stripe removal methods from TomoPy to CuPy

### PR DESCRIPTION
**Pull request by yousefmoazzam**
This PR will be providing CuPy ports of the methods mentioned in item 1 from #22.

### CODE REVIEW

**Comment by yousefmoazzam** [comment]
@dkazanc @namannimmo10 Heads-up, the port of dead stripe removal involves something that people may find a bit dodgy, please read the commit message for e18feaf and let me know if you think an alternative should be done instead!

**Comment by dkazanc** [comment]
@yousefmoazzam I think it is fine to use the ported function for now but we need to make a mark that it should be replaced with the 12.0 rlease of CuPy?

**Comment by yousefmoazzam** [comment]
@dkazanc Yep, that makes sense. I've put code comments in the method https://github.com/DiamondLightSource/httomolib/blob/0f4e060b4510efd42450aa199cf4217475d21896/src/httomolib/prep/stripe.py#L247-L250 and at the top of the copied file https://github.com/DiamondLightSource/httomolib/blob/0f4e060b4510efd42450aa199cf4217475d21896/src/httomolib/prep/_rgi.py#L1-L4 but if there is clearer/more obvious way to mark it then feel free to do so.

**Comment by dkazanc** [comment]
@yousefmoazzam I guess we have now a few hidden functions in the `remove_all_stripe` module ported from TomoCuPy. We can probably turn them into separate methods, which is a different task. We probably then close this PR and make a separate issue on extracting sub-methods from  `remove_all_stripe` into separate exposed modules?

**Comment by yousefmoazzam** [comment]
Yeah, this is pretty outdated, so I'm happy to close this in favour of what you've suggested.

**Pull request closed without merging**
